name = "DataAugmentation"
uuid = "88a5189c-e7ff-4f85-ac6b-e6158070f02e"
authors = ["lorenzoh <lorenz.ohly@gmail.com>"]
version = "0.1.0"

[deps]
ColorBlendModes = "60508b50-96e1-4007-9d6c-f475c410f16b"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ImageDraw = "4381153b-2b60-58ae-a1ba-fd683676385f"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = ">= 1.3"

[publish]
theme = "./theme/"
title = "DataAugmentation.jl"
